module.exports=[
    {
        module:'jquery',
        entry:'https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js',
        global:'jQuery'
    },
    {
        module:'pixi.js',
        entry:'https://cdn.bootcss.com/pixi.js/5.0.4/pixi.min.js',
        global:'PIXI'
    },
    {
        module:'TweenMax',
        entry:'https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.3/TweenMax.min.js',
        global:'TweenMax'
    },
    {
        module:'swiper',
        entry:'https://cdn.bootcss.com/Swiper/4.5.0/js/swiper.min.js',
        global:'Swiper'
    },
    {
        module:'swipercss',
        entry:'https://cdn.bootcss.com/Swiper/4.5.0/css/swiper.min.css',
        global:'css'
    }
]


